// tasks/seed.js  (ES module)
import { dbConnection, closeConnection } from "../config/mongoConnection.js";
import { users, themes, portfolios, messages } from "../data/index.js";
import bcrypt from "bcrypt";

const main = async () => {
  const db = await dbConnection();
  await db.dropDatabase();

  console.log("Starting to seed database...");

  // Create sample users
  console.log("Creating users...");
  const user1 = await users.createUser(
    "devwalker",
    "walker.dev@example.com",
    "Password123!"
  );

  const user2 = await users.createUser(
    "janesmith",
    "jane.smith@example.com",
    "Secure456!"
  );

  const user3 = await users.createUser(
    "alexrivera",
    "alex.r@example.com",
    "StrongPwd789!"
  );

  console.log("Users created successfully");

  // Create sample themes
  console.log("Creating themes...");
  const theme1 = await themes.createTheme(
    null,
    "Modern Minimal",
    {
      primaryColor: "#1F2937",
      accentColor: "#3B82F6",
      background: "#F9FAFB",
      fontFamily: "Inter",
    },
    true
  );

  const theme2 = await themes.createTheme(
    null,
    "Dark Professional",
    {
      primaryColor: "#111827",
      accentColor: "#6D28D9",
      background: "#1F2937",
      fontFamily: "Roboto",
    },
    true
  );

  const theme3 = await themes.createTheme(
    null,
    "Vibrant Creative",
    {
      primaryColor: "#4F46E5",
      accentColor: "#EC4899",
      background: "#FFFFFF",
      fontFamily: "Poppins",
    },
    true
  );

  // a small user theme
  const theme4 = await themes.createTheme(
    user1._id,
    "My Custom Theme",
    {
      primaryColor: "#047857",
      accentColor: "#F59E0B",
      background: "#ECFDF5",
      fontFamily: "Montserrat",
    },
    false
  );

  console.log("Themes created successfully");

  // Create sample portfolios (1 each, more will be added below if needed)
  console.log("Creating portfolios...");

  // portfolio for user1
  const portfolio1 = await portfolios.createPortfolio(
    user1._id,
    "Walker's Software Portfolio",
    "Showcasing my best engineering projects and open source work.",
    [
      /* trimmed details — keep as you currently have */
      {
        type: "project",
        items: [
          {
            title: "Portfolio Builder",
            description: "A small demo project",
            technologies: ["Node.js"],
            order: 1,
          },
        ],
      },
    ],
    { singlePage: true, pages: [] },
    theme1._id,
    true,
    "walker.dev@example.com",
    true
  );

  // portfolio for user2
  const portfolio2 = await portfolios.createPortfolio(
    user2._id,
    "Jane's UX Design Portfolio",
    "A showcase of my user experience design work and case studies.",
    [
      {
        type: "project",
        items: [
          {
            title: "Design Case Study",
            description: "A short case study",
            technologies: ["Figma"],
            order: 1,
          },
        ],
      },
    ],
    { singlePage: false, pages: [] },
    theme2._id,
    true,
    "jane.smith@example.com",
    false
  );

  // portfolio for user3 (clone or small portfolio)
  const portfolio3 = await portfolios.createPortfolio(
    user3._id,
    "Alex's Developer Portfolio",
    "My journey as a full-stack developer and the projects I've built.",
    [
      {
        type: "project",
        items: [
          {
            title: "API Project",
            description: "A REST API sample",
            technologies: ["Node.js", "Express"],
            order: 1,
          },
        ],
      },
    ],
    { singlePage: true, pages: [] },
    theme3._id,
    true,
    "alex.r@example.com",
    false
  );

  console.log("Initial portfolios created.");

  // --- NEW: ensure every user has at least 2 portfolios ---
  // We'll check each created user; if they have <2 portfolios, create a simple second portfolio for them.
  const ensureSecondPortfolio = async (userObj, index) => {
    const userId = userObj._id;
    const existing = await portfolios.getPortfoliosByUserId(userId);
    if (!existing || existing.length < 2) {
      const p = await portfolios.createPortfolio(
        userId,
        `${userObj.username}'s Extra Portfolio`,
        `Second portfolio generated by seed (user ${userObj.username})`,
        [
          {
            type: "custom",
            items: [
              {
                title: "About this portfolio",
                content: `<p>Auto-generated sample portfolio #2 for ${userObj.username}</p>`,
                order: 1,
              },
            ],
          },
        ],
        { singlePage: true, pages: [] },
        index === 1 ? theme1._id : index === 2 ? theme2._id : theme3._id,
        false,
        null,
        false
      );
      console.log(`Created extra portfolio for ${userObj.username}: ${p._id}`);
      // set active to the first portfolio if user had none active
      const updated = await users.getUserById(userId);
      if (!updated.activePortfolioId) {
        // set active to the first portfolio
        const firstId = existing && existing[0] ? existing[0]._id : p._id;
        await users.updateActivePortfolio(userId, firstId);
      }
    } else {
      console.log(
        `${userObj.username} already has ${existing.length} portfolios — skipping.`
      );
    }
  };

  await ensureSecondPortfolio(user1, 1);
  await ensureSecondPortfolio(user2, 2);
  await ensureSecondPortfolio(user3, 3);

  console.log("Ensured all users have at least two portfolios.");

  // Create sample messages (optional)
  console.log("Creating messages...");
  await messages.createMessage(
    portfolio1._id,
    "Alex Rivera",
    "alex.r@example.com",
    "Hi! I loved your portfolio and would like to discuss a collaboration."
  );

  await messages.createMessage(
    portfolio2._id,
    "Michael Johnson",
    "michael.j@example.com",
    "Hello Jane, I'm impressed by your UX work."
  );

  console.log("Messages created successfully");

  console.log("Done seeding database");
  await closeConnection();
};

main().catch((error) => {
  console.error(error);
  closeConnection();
});
